spring:
  application:
    name: hackathon-auth
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/hackathondb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  web:
    resources:
      add-mappings: true

jwt:
  secret: postechHackathon2026SecretKey12345
  refresh-token-expiration: 900000
  access-token-expiration: 604800000

cors:
  allowed-origins: http://localhost:3000,http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"
  allow-credentials: true